<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cyc</string>
	</array>
	<key>name</key>
	<string>Cyclang</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#booleans</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.cyclang</string>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.cyclang</string>
					<key>match</key>
					<string>\b(if|else|while|for|return)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.cyclang</string>
					<key>match</key>
					<string>\b(fn|let)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.cyclang</string>
					<key>match</key>
					<string>\b(nil|true|false)\b</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.builtin.cyclang</string>
					<key>match</key>
					<string>\b(print|len)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function.cyclang</string>
					<key>match</key>
					<string>\b([a-zA-Z_][a-zA-Z0-9_]*)\s*(?=\()</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.type.primitive.cyclang</string>
					<key>match</key>
					<string>\b(i32|i64|bool|string)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.list.cyclang</string>
					<key>match</key>
					<string>\bList\b</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.cyclang</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.cyclang</string>
							<key>match</key>
							<string>\\(n|t|r|\\|"|')</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.cyclang</string>
					<key>match</key>
					<string>\b-?[0-9]+\b</string>
				</dict>
			</array>
		</dict>
		<key>booleans</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.cyclang</string>
					<key>match</key>
					<string>\b(true|false)\b</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.cyclang</string>
					<key>match</key>
					<string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.cyclang</string>
					<key>match</key>
					<string>(\+\+|--|\+|-|\*|/|\^)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.cyclang</string>
					<key>match</key>
					<string>=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.cyclang</string>
					<key>match</key>
					<string>!</string>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.cyclang</string>
					<key>match</key>
					<string>;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.cyclang</string>
					<key>match</key>
					<string>,</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.section.braces.cyclang</string>
					<key>match</key>
					<string>[{}]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.section.brackets.cyclang</string>
					<key>match</key>
					<string>[\[\]]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.cyclang</string>
					<key>match</key>
					<string>[()]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.type.cyclang</string>
					<key>match</key>
					<string>:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.return-type.cyclang</string>
					<key>match</key>
					<string>-&gt;</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cyclang</string>
	<key>uuid</key>
	<string>9A1B2C3D-4E5F-6A7B-8C9D-0E1F2A3B4C5D</string>
</dict>
</plist>
