expression = _ { primary }
primary = _ { bool | "nil" | number | string | name }
name = { (alpha ~ (alpha | digit | "_")*) }
number = { ("-" ~ digits) | digits }
digits = { digit+ }
digit = { ASCII_DIGIT }
alpha = { ASCII_ALPHA | "_" }
bool = { "true" | "false" }
string = { "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
operator = _{ add | subtract | multiply | divide | power | equalequal }
add = { "+" }
subtract = { "-" }
multiply = { "*" }
divide = { "/" }
power = { "^" }
equalequal = { "==" }
equal = { "=" }
WHITESPACE = _{ " " | "\t" }