
expression = _ { base_expr }
base_expr = { primary | let_stmt }
primary = {bool | number | string | name}
line_stmt = {primary ~ semicolon}
let_stmt = { "let" ~ WHITESPACE? ~ name ~ WHITESPACE? ~ "=" ~ WHITESPACE? ~ primary ~ semicolon }
name = { (alpha ~ (alpha | digit | "_")*) }
number = { ("-" ~ digits) | digits }
digits = { digit+ }
digit = { ASCII_DIGIT }
alpha = { ASCII_ALPHA | "_" }
bool = { "true" | "false" }
string = { "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
operator = _{ add | subtract | multiply | divide | power | equalequal }
add = { "+" }
subtract = { "-" }
multiply = { "*" }
divide = { "/" }
power = { "^" }
equalequal = { "==" }
equal = { "=" }
semicolon = { ";" }
WHITESPACE = _{ " " | "\t" }
