program = _ { SOI ~ stmt ~ EOI }
stmt = _ { expression }
expression = _ { primary ~ (WHITESPACE? ~ operator ~ WHITESPACE? ~ primary)? }
primary = _ { "true" | "false" | "nil" | number | string | name }
name = { (alpha ~ (alpha | digit | "_")*) }
number = { ("-" ~ digits) | digits }
digits = { digit+ }
digit = { ASCII_DIGIT }
alpha = { ASCII_ALPHA | "_" }
string = { "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
operator = _{ add | subtract | multiply | divide | power | equalequal }
add = { "+" }
subtract = { "-" }
multiply = { "*" }
divide = { "/" }
power = { "^" }
equalequal = { "==" }
equal = { "=" }
WHITESPACE = _{ " " | "\t" }